In [1]:
import torch

In [2]:
x = torch.randn(1)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

y = torch.ones_like(x, device=device)

x = x.to(device)

z = x + y

z.to('cpu', torch.double)

tensor([1.3059], dtype=torch.float64)

In [6]:
a = torch.randn(1, 3, 3)
b = torch.randn(1, 3, 3)
print(a)
print(b)
c = torch.cat((a, b), dim=0)
print(c)

tensor([[[-0.0816, -0.0053,  0.3465],
         [ 1.7145,  0.5614, -0.7563],
         [ 0.3232, -0.3231,  0.3362]]])
tensor([[[ 0.9967,  1.9108, -0.3362],
         [-0.4080,  0.5646, -1.1161],
         [ 0.6086, -0.3384,  0.0192]]])
tensor([[[-0.0816, -0.0053,  0.3465],
         [ 1.7145,  0.5614, -0.7563],
         [ 0.3232, -0.3231,  0.3362]],

        [[ 0.9967,  1.9108, -0.3362],
         [-0.4080,  0.5646, -1.1161],
         [ 0.6086, -0.3384,  0.0192]]])


In [12]:
a = torch.ones(7)
print(a.numpy())
b = a.add(1)
b = a.add_(1)
print(a, b)

[1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.]) tensor([2., 2., 2., 2., 2., 2., 2.])


In [17]:
a = torch.randn(3, 3)
a = a * 3
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

False
True
tensor(63.6335, grad_fn=<SumBackward0>)


In [26]:
x = torch.ones(3, 3, requires_grad=True)

y = x + 5
z = y * y
out = z.mean()
print(x, y, z, out)
print("##################")
out.backward()
print(x, y, z, out)
print("##################")
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True) tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>) tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)
##################
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True) tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>) tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)
##################
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [27]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


In [31]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
