In [32]:
import torch
import numpy as np

In [24]:
x = torch.empty(2, 2)
x

tensor([[1.0788e-34, 0.0000e+00],
        [5.0447e-44, 0.0000e+00]])

In [25]:
x = torch.rand(2, 2)
x

tensor([[0.2072, 0.5113],
        [0.0272, 0.6227]])

In [26]:
y = torch.rand(2, 2)
y

tensor([[0.5472, 0.0864],
        [0.6335, 0.6671]])

In [27]:
z = torch.sub(x, y)
z

tensor([[-0.3400,  0.4249],
        [-0.6063, -0.0444]])

In [29]:
x[1, 1].item()

0.6226696372032166

In [30]:
a = torch.ones(2, 2)
b = a.numpy
a, b

(tensor([[1., 1.],
         [1., 1.]]), <function Tensor.numpy>)

In [31]:
a.add_(1)
a, b

(tensor([[2., 2.],
         [2., 2.]]), <function Tensor.numpy>)

In [44]:
a = np.ones(5)
b = torch.from_numpy(a)
a, b

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [46]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to("cpu") # gpu tensor is not avalable to convert to numpy
  z.numpy()

In [47]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [51]:
x = torch.randn(3)
y = torch.randn(3, requires_grad=True)
x, y

(tensor([ 0.1002,  1.5288, -0.1804]),
 tensor([0.8973, 1.3415, 0.3568], requires_grad=True))

In [53]:
x = torch.ones(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
print(z)
z = z.mean()
print(z)

z.backward()
print(x.grad)

tensor([1., 1., 1.], requires_grad=True)
tensor([3., 3., 3.], grad_fn=<AddBackward0>)
tensor([18., 18., 18.], grad_fn=<MulBackward0>)
tensor(18., grad_fn=<MeanBackward0>)
tensor([4., 4., 4.])
