In [ ]:
import torch

# Tensor

In [ ]:
t = torch.tensor([0, 1, 2, 3], dtype=torch.float64)
t, t.dim(), t.shape, t.size()

(tensor([0., 1., 2., 3.], dtype=torch.float64),
 1,
 torch.Size([4]),
 torch.Size([4]))

In [ ]:
t.mean(), t.max(), t.std(), t.max(dim=0)[1]

(tensor(1.5000, dtype=torch.float64),
 tensor(3., dtype=torch.float64),
 tensor(1.2910, dtype=torch.float64),
 tensor(3))

In [ ]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t.shape)
t = t.view([3, -1])
t

torch.Size([2, 3])


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[3, 4], [5, 6]])
torch.cat([a, b], dim=1), torch.stack([a, b])

(tensor([[1, 2, 3, 4],
         [3, 4, 5, 6]]), tensor([[[1, 2],
          [3, 4]],
 
         [[3, 4],
          [5, 6]]]))

In [ ]:
a = torch.tensor([[1, 2], [3, 4]])
torch.ones_like(a)

tensor([[1, 1],
        [1, 1]])

In [ ]:
a.mul_(2), a

(tensor([[2, 4],
         [6, 8]]), tensor([[2, 4],
         [6, 8]]))

# 선형회귀

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [ ]:
x_train = torch.tensor([[1], [2], [3]], dtype=torch.float64)
y_train = torch.tensor([[2], [4], [6]], dtype=torch.float64)

W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

for epoch in range(4001):
  h = W * x_train + b

  cost = torch.mean((h - y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch%500 == 0:
    print(W, b)

tensor([0.1867], requires_grad=True) tensor([0.0800], requires_grad=True)
tensor([1.9029], requires_grad=True) tensor([0.2207], requires_grad=True)
tensor([1.9709], requires_grad=True) tensor([0.0663], requires_grad=True)
tensor([1.9913], requires_grad=True) tensor([0.0199], requires_grad=True)
tensor([1.9974], requires_grad=True) tensor([0.0060], requires_grad=True)
tensor([1.9992], requires_grad=True) tensor([0.0018], requires_grad=True)
tensor([1.9998], requires_grad=True) tensor([0.0005], requires_grad=True)
tensor([1.9999], requires_grad=True) tensor([0.0002], requires_grad=True)
tensor([2.0000], requires_grad=True) tensor([4.8930e-05], requires_grad=True)


In [ ]:
w = torch.tensor(3.0, requires_grad=True)
y = w**2
z = 2*y + 5
z.backward()
w.grad.item()

12.0

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x1_train = torch.tensor([[73], [93], [89], [96], [73]], dtype=torch.float64)
x2_train = torch.tensor([[80], [88], [91], [98], [66]], dtype=torch.float64)
x3_train = torch.tensor([[75], [93], [90], [100], [70]], dtype=torch.float64)
y_train = torch.tensor([[152], [185], [180], [196], [142]], dtype=torch.float64)

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

num_epochs = 1000
for epoch in range(num_epochs + 1):
  
  h = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

  cost = torch.mean((h - y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
    print(cost.item())

29661.8
1.5636266993202028
1.4976090681738992
1.4350347932366598
1.3757249620943237
1.3195076303664979
1.2662184519273065
1.215703938979828
1.1678203210994078
1.1224258884670046
1.0793910061261678


In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                        [93, 88, 93],
                        [89, 91, 80],
                        [96, 98, 100],
                        [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1e-5)

EPOCHS = 20
for epoch in range(EPOCHS + 1):

  h = x_train.matmul(W) + b

  cost = torch.mean((h - y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print(f"epoch : {epoch} cost : {cost.item()}")

epoch : 0 cost : 29661.80078125
epoch : 1 cost : 9537.6943359375
epoch : 2 cost : 3069.590087890625
epoch : 3 cost : 990.6702880859375
epoch : 4 cost : 322.48187255859375
epoch : 5 cost : 107.7170639038086
epoch : 6 cost : 38.687496185302734
epoch : 7 cost : 16.499042510986328
epoch : 8 cost : 9.365655899047852
epoch : 9 cost : 7.071113586425781
epoch : 10 cost : 6.331847190856934
epoch : 11 cost : 6.092532157897949
epoch : 12 cost : 6.013816833496094
epoch : 13 cost : 5.986784934997559
epoch : 14 cost : 5.976325035095215
epoch : 15 cost : 5.971208095550537
epoch : 16 cost : 5.967835426330566
epoch : 17 cost : 5.964968681335449
epoch : 18 cost : 5.962291240692139
epoch : 19 cost : 5.959664344787598
epoch : 20 cost : 5.957088947296143


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model = nn.Linear(1, 1)

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

EPOCHS = 2000
for epoch in range(EPOCHS+1):
  
  pred = model(x_train)

  cost = F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(epoch, cost.item())

0 13.103541374206543
100 0.00279058120213449
200 0.00172441138420254
300 0.0010655784280970693
400 0.0006584661896340549
500 0.0004068926500622183
600 0.0002514346851967275
700 0.00015537298168055713
800 9.601024794392288e-05
900 5.9327696362743154e-05
1000 3.66610438504722e-05
1100 2.2655576685792767e-05
1200 1.3999051589053124e-05
1300 8.65114816406276e-06
1400 5.346103989722906e-06
1500 3.3032331430149497e-06
1600 2.04174443751981e-06
1700 1.2618406799447257e-06
1800 7.801028800713539e-07
1900 4.823282324650791e-07
2000 2.982416447139258e-07


In [ ]:
model(torch.FloatTensor([4.0]))

tensor([7.9989], grad_fn=<AddBackward0>)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset, DataLoader

x_train = torch.FloatTensor([[73, 80, 75],
                        [93, 88, 93],
                        [89, 91, 80],
                        [96, 98, 100],
                        [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

dataset = TensorDataset(x_train, y_train)

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

for epoch in range(21):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples

    pred = model(x_train)

    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print(epoch, batch_idx+1, cost.item())

0 1 40594.3125
0 2 13990.65234375
0 3 4648.916015625
1 1 1530.466552734375
1 2 386.6463623046875
1 3 26.38023567199707
2 1 99.57803344726562
2 2 12.72589111328125
2 3 3.2893059253692627
3 1 15.019401550292969
3 2 2.303422212600708
3 3 12.519131660461426
4 1 10.322033882141113
4 2 3.2436087131500244
4 3 3.242593288421631
5 1 9.361555099487305
5 2 4.587904453277588
5 3 0.059433404356241226
6 1 7.686336517333984
6 2 11.683297157287598
6 3 0.05709836259484291
7 1 9.803659439086914
7 2 4.124814987182617
7 3 0.0001790768001228571
8 1 4.0361504554748535
8 2 2.1512694358825684
8 3 18.558195114135742
9 1 5.668358325958252
9 2 6.14703893661499
9 3 10.522567749023438
10 1 3.2428829669952393
10 2 2.5823814868927
10 3 18.811073303222656
11 1 6.175918102264404
11 2 4.039100646972656
11 3 14.795418739318848
12 1 4.262564659118652
12 2 7.18346643447876
12 3 9.24424934387207
13 1 4.120095252990723
13 2 1.5358551740646362
13 3 19.780071258544922
14 1 5.871580123901367
14 2 7.286798477172852
14 3 11.7586

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = [[1], [2], [3]]
    self.y_data = [[2], [4], [6]]

  def __len__(self):
    return len(self.x_data)
  
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = nn.Linear(1, 3)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

EPOCHS = 1000
for epoch in range(EPOCHS + 1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples

    pred = model(x_train)

    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
      print(epoch, batch_idx, cost.item())

0 0 13.882022857666016
0 1 43.78351974487305


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: UserWarning: Using a target size (torch.Size([2, 1])) that is different to the input size (torch.Size([2, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: UserWarning: Using a target size (torch.Size([1, 1])) that is different to the input size (torch.Size([1, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.


100 0 0.034864138811826706
100 1 0.025958314538002014
200 0 0.025685740634799004
200 1 0.01741066761314869
300 0 0.019067207351326942
300 1 0.011419601738452911
400 0 0.004533539060503244
400 1 0.026457272469997406
500 0 0.012452110648155212
500 1 0.0005656497669406235
600 0 0.00732765719294548
600 1 0.004051035735756159
700 0 0.006427066866308451
700 1 0.0006155986338853836
800 0 0.004620220046490431
800 1 0.0004768551152665168
900 0 0.00271586119197309
900 1 0.0016956784529611468
1000 0 0.0006596778403036296
1000 1 0.0038111601024866104


# 로지스틱 회귀

In [1]:
import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import matplotlib.pyplot as plt
import random

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

random.seed(777)
torch.manual_seed(777)
if device == "cuda":
  torch.cuda.manual_seed_all(777)

EPOCHS = 15
batch_size = 500

mnist_train = dsets.MNIST(root='mnist/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)
mnist_test = dsets.MNIST(root='mnist/',
                        train=False,
                        transform=transforms.ToTensor(),
                         download=True)

dataloader = DataLoader(dataset=mnist_train,
                        batch_size=batch_size,
                        shuffle=True,
                        drop_last=True)

model = nn.Linear(784, 10, bias=True).to(device)

criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for epoch in range(EPOCHS + 1):

  avg_cost = 0
  total_batch = len(dataloader)

  for X, y in dataloader:
    X = X.view(-1, 28* 28).to(device)
    y = y.to(device)

    optimizer.zero_grad()
    h = model(X)
    cost = criterion(h, y)
    cost.backward()
    optimizer.step()

    avg_cost += cost / total_batch

  print(epoch, avg_cost)

print("finished")

0 tensor(0.8994, grad_fn=<AddBackward0>)
1 tensor(0.5117, grad_fn=<AddBackward0>)
2 tensor(0.4436, grad_fn=<AddBackward0>)
3 tensor(0.4102, grad_fn=<AddBackward0>)
4 tensor(0.3892, grad_fn=<AddBackward0>)
5 tensor(0.3746, grad_fn=<AddBackward0>)
6 tensor(0.3634, grad_fn=<AddBackward0>)
7 tensor(0.3546, grad_fn=<AddBackward0>)
8 tensor(0.3473, grad_fn=<AddBackward0>)
9 tensor(0.3414, grad_fn=<AddBackward0>)
10 tensor(0.3363, grad_fn=<AddBackward0>)
11 tensor(0.3316, grad_fn=<AddBackward0>)
12 tensor(0.3278, grad_fn=<AddBackward0>)
13 tensor(0.3244, grad_fn=<AddBackward0>)
14 tensor(0.3212, grad_fn=<AddBackward0>)
15 tensor(0.3184, grad_fn=<AddBackward0>)
finished


In [6]:
with torch.no_grad():
  x_test = mnist_test.test_data.view(-1, 28 * 28).float().to(device)
  y_test = mnist_test.test_labels.to(device)

  pred = model(x_test)
  correct = torch.argmax(pred, 1) == y_test
  acc = correct.float().mean()
  print(acc.item())

0.9057000279426575


/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:80: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:70: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


# 인공 신경망